language: java
jdk:
  - openjdk8 #Oracle JDK 8 is not working on Travis CI
  - openjdk9 #Oracle JDK 9 is not working on Travis CI
  - openjdk10
  - openjdk11 #LTS
  - openjdk12
  - openjdk13
  - openjdk14
script: mvn test -B -Pno-frontend-build #Angular 9 does not build cleanly on Travis CI
